version: '3.8'

services:
  app:
    build: .
    ports:
      - '3010:3010'
    environment:
      - MONGO_URI=mongodb://admin:admin@mongo:27017/bancoTechChallenge2?authSource=admin
      - JWT_SECRET=k2w9R!v7$zYpF%jX#rL3u8TbAqXeShV0
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    restart: always
    command: npm run start:dev

  mongo:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

volumes:
  mongo-data:
